
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-prod
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: 'https://github.com/eduardolmedeiros/hello-app-go-sample'
    path: helm-chart
    targetRevision: HEAD
    helm:
      values: |
        service:
          type: NodePort
          port: 8080

        serviceAccount:
          create: true
          name: "hello-app-go-sample"

        image:
          repository: emedeiros/hello-app-go-sample
          tag: "0.1"

        replicaCount: 4
        autoscaling:
          enabled: true
          minReplicas: 2
          maxReplicas: 4
          targetCPUUtilizationPercentage: 80
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:     # Sync options which modifies sync behavior
      - CreateNamespace=true # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: production
